INSERT INTO PERSON (ID,NAME,LOCATION,BIRTH_DATE)
VALUES(1001, 'Rohit', 'GDL', sysdate());

INSERT INTO Course (ID,NAME)
VALUES(1001, 'Learning JPA');

INSERT INTO Course (ID,NAME)
VALUES(1002, 'JPA testing');